Create a correctly-sized slice to proxy *uint16
Fixes the below issue seen in the containerd test suite.
```
fatal error: checkptr: converted pointer straddles multiple allocations
```

Also adds `-gcflags=all=-d=checkptr` to all the test runs on CI, to
avoid this regressing in future. This requires testing with Go 1.14 or
newer, so CI now runs on Go 1.15, as Go 1.14 did not recommend using
checkptr on Windows.

And _that_ requires the Visual Studio 2019 build image on AppVeyor.

Signed-off-by: Paul "TBBle" Hampson <Paul.Hampson@Pobox.com>